name: Test Suite for NVIDIA operators

on:
  - pull_request

jobs:
  call-inclusive-naming-check:
    name: Inclusive naming
    uses: canonical/inclusive-naming/.github/workflows/woke.yaml@main
    with:
      fail-on-error: "true"

  lint-unit:
    name: Lint Unit
    uses: charmed-kubernetes/workflows/.github/workflows/lint-unit.yaml@main
    needs:
      - call-inclusive-naming-check
    with:
      python: "['3.10', '3.11']"
